Update egg-a-i-o.json
DanBot-Hosting/pterodactyl-eggs pull request #6
Opened 2022-01-07 19:34 UTC by James-Discord

2022-01-07 20:26 UTC, itzJOHv commented
edit name change to `All In One`?

2022-01-10 15:39 UTC, vinc3nz requested changes
Dirt. Does nothing and there now is a mistake. It's not `your the server`

2022-01-10 16:27 UTC, itzJOHv requested changes

2022-01-10 16:27 UTC, itzJOHv commented on egg-a-i-o.json
> +    "name": "AIO (ALL IN ONE)",
```diff
-    "name": "AIO (ALL IN ONE)",
+    "name": "AIO (All In One)",
```

2022-01-10 16:27 UTC, djohts commented on egg-a-i-o.json
> +            "description": "The startup command for your the server to use",
```diff
-            "description": "The startup command for your the server to use",
+            "description": "The startup command for your server to use",
```

2022-09-20 21:12 UTC, closed without merging